version: '3.8'

services:
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: lsegtest
      MARIADB_USER: lsegDBAdmin
      MARIADB_PASSWORD: lsegpassword
    ports:
      - "3306:3306"
    volumes:
      - ./localDatabase.sql:/docker-entrypoint-initdb.d/localDatabase.sql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/lsegtest
      SPRING_DATASOURCE_USERNAME: lsegDBAdmin
      SPRING_DATASOURCE_PASSWORD: lsegpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: none

volumes:
  mariadb_data:
